{% set name = "pystore" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ae3e3444ed9b06702bc0bfb6d1df60dc3df93ca271d1b9d85c82b27c9e81f4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cloudpickle
    - dask-core
    - distributed
    - fastparquet
    - multitasking >=0.0.11
    - numpy <2.0.0,>=1.24.0
    - pandas
    - partd
    - python >={{ python_min }}
    - python-snappy
    - toolz
    - pyarrow

test:
  imports:
    - pystore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ranaroussi/pystore
  summary: Fast data store for Pandas timeseries data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
