{% set name = "pystore" %}
{% set version = "0.1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abe99682d2da83a6619077c34f9ca7117680d5e98923f35a6e0457fcfe8ac43b
  patches:
    - entry.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle
    - dask-core
    - distributed
    - fastparquet
    - multitasking
    - numpy
    - pandas
    - partd
    - python >=3.6
    - python-snappy
    - toolz

test:
  imports:
    - pystore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ranaroussi/pystore
  summary: Fast data store for Pandas timeseries data
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
